# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/myservice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13src/myservice.proto\x12\tmyservice\"\x07\n\x05\x45mpty\"\x1e\n\rEventResponse\x12\r\n\x05\x65vent\x18\x01 \x01(\t2I\n\tMyService\x12<\n\x0eGetRandomEvent\x12\x10.myservice.Empty\x1a\x18.myservice.EventResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.myservice_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=34
  _globals['_EMPTY']._serialized_end=41
  _globals['_EVENTRESPONSE']._serialized_start=43
  _globals['_EVENTRESPONSE']._serialized_end=73
  _globals['_MYSERVICE']._serialized_start=75
  _globals['_MYSERVICE']._serialized_end=148
# @@protoc_insertion_point(module_scope)
